### ISSUE TITLE
katex types seemingly not cacheable

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno-gfm#59] opened 2023-04-03 00:17 UTC
I've tried using this lib in both a plain Deno script and in a Deno Fresh project. In every run / watch-triggered reload, I see the following re-download: `https://esm.sh/v113/@types/katex@0.1
6.0/dist/katex.mjs~.d.ts`. Life could be worse... it takes barely 5 seconds. Still, would be good to look into this dep / enabling its caching.

**Comment by lino-levan** [comment] 2023-07-04 18:27
@hashrock can you reproduce? I am unable to. I think https://github.com/denoland/deno/pull/19392 fixed this.

**Comment by marvinhagemeister** [comment] 2023-07-04 18:42
I think this can be closed. I ran into this a couple of times with older deno versions but I don't see this anymore since https://github.com/denoland/deno/pull/19392 landed.

**Closed** 2023-07-04 18:58 UTC
